Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          backupLogger:
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                 logFileURL: '%FLOW_PATH_DATA%Logs/Backup.log'
                 createParentDirectories: true
                 severityThreshold: '%LOG_INFO%'
                 maximumLogFileSize: 10485760
                 logFilesToKeep: 1
