name: 'Build & Deploy Documentation'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Setup NodeJs'
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'Install dependencies'
      run: npm -v && npm install
    - name: 'Build documentation'
      run: npm run docs:prod
    - name: 'Deploy to GitHub-Pages'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: Documentation/.vuepress/dist
